import {test,expect} from '@playwright/test';
const workbook=process.env.WINE_TEST_COLUMN_G_WORKBOOK;
test('actual column G workbook imports every valid rating, preserves provenance and survives reload/reimport',async({page})=>{
 test.skip(!workbook,'Set WINE_TEST_COLUMN_G_WORKBOOK to the supplied eight-column workbook.');test.setTimeout(120000);
 await page.route('**/api/**',r=>r.fulfill({status:404,body:'{}'}));await page.goto('/');
 const upload=async()=>{await page.getByRole('button',{name:'Import data',exact:true}).click();await page.getByLabel('Excel, CSV or JSON file').setInputFiles(workbook);await page.getByRole('button',{name:'Validate and import',exact:true}).click();await expect(page.locator('[name="column-6"]')).toHaveValue('ratings');await expect(page.locator('[name="column-4"]')).toHaveValue('raw_title');await expect(page.locator('[name="column-5"]')).toHaveValue('price');await page.getByRole('button',{name:'Confirm Excel import',exact:true}).click();await expect(page.locator('#engine-dialog')).not.toBeVisible({timeout:60000});await expect(page.locator('#engine-result-count')).toContainText('8645');};
 const summary=()=>page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('wine-intelligence',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const s=await new Promise(resolve=>{const r=db.transaction('engine').objectStore('engine').get('wine-intelligence.v1');r.onsuccess=()=>resolve(r.result);});db.close();return {listings:s.listings.length,reviews:s.reviews.length,ids:s.reviews.map(r=>r.id).sort(),molesworth:s.reviews.filter(r=>r.reviewer==='James Molesworth').length,allRetailer:s.reviews.every(r=>r.verification==='retailer_reported'&&!r.verified),worksheet:s.reviews.every(r=>r.importProvenance?.worksheet==='Inventory' && r.importProvenance?.column==='G'),warnings:s.listings.reduce((n,l)=>n+l.criticWarnings.length,0),notRated:s.listings.reduce((n,l)=>n+l.notRatedCritics.length,0)};});
 await upload();const before=await summary();expect(before).toMatchObject({listings:8645,reviews:4747,molesworth:63,allRetailer:true,worksheet:true,warnings:8,notRated:6});await page.reload();await expect(page.locator('#engine-result-count')).toContainText('8645',{timeout:60000});expect(await summary()).toEqual(before);await upload();expect(await summary()).toEqual(before);
 await page.getByRole('searchbox',{name:'Search inventory',exact:true}).fill('Angelus');await page.locator('#engine-results tbody tr').first().getByRole('button',{name:'Professional critics',exact:true}).click();await expect(page.locator('#engine-dialog')).toContainText('Original ratings cell');await expect(page.locator('#engine-dialog')).toContainText('column G');
});
