import { test,expect } from '@playwright/test';
const wine={raw_title:'Synthetic Producer X Wine Y 2019 750ml',producer:'Synthetic Producer X',cuvee:'Wine Y',vintage:2019,format:'750ml',region:'Bordeaux',appellation:'Pauillac',country:'France',type:'Red',price:300,price_terms:'ex_tax',ratings:'WA 98'};
async function upload(page,sourceId,rows) {await page.getByRole('button',{name:'Import data',exact:true}).click();await page.getByRole('combobox',{name:'Import source',exact:true}).selectOption(sourceId);await page.getByLabel('Excel, CSV or JSON file').setInputFiles({name:'synthetic-market-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({rows}))});await page.getByRole('button',{name:'Validate and import',exact:true}).click();await expect(page.locator('#engine-dialog')).not.toBeVisible();}
test.beforeEach(async({page})=>{await page.route('**/api/**',r=>r.fulfill({status:404,body:'{}'}));await page.goto(process.env.WINE_TEST_URL || '/');});
test('exact current offers drive median; rejected sold, stale, auction and format candidates remain inspectable',async({page})=>{
  await upload(page,'flickinger',[wine]);const now=new Date().toISOString();
  const offer=(price,merchant,fields={})=>({...wine,price,merchant,source_url:`https://${merchant.toLowerCase()}.example/wine-y`,merchant_country:'US',merchant_confidence:1,availability_status:'CONFIRMED_IN_STOCK',availability_verified:true,verified_at:now,verification_method:'merchant_feed',verification_evidence:'SYNTHETIC TEST ONLY',...fields});
  await upload(page,'market-import',[offer(400,'A'),offer(420,'B'),offer(410,'C'),offer(250,'Sold',{availability_status:'SOLD',is_available:false}),offer(270,'Auction',{offer_type:'historical_auction',sale_type:'auction'}),offer(280,'Year',{vintage:2018,raw_title:'Synthetic Producer X Wine Y 2018 750ml'}),offer(600,'Magnum',{format:'1.5L',raw_title:'Synthetic Producer X Wine Y 2019 1.5L'}),offer(240,'Stale',{verified_at:new Date(Date.now()-72*3600000).toISOString()})]);
  const results=page.locator('#engine-results');await expect(results).toContainText('$410.00');await expect(results).toContainText('26.8%');await expect(results).toContainText('3 confirmed merchant comps');
  await results.getByRole('button',{name:'Market Intelligence',exact:true}).click();const dialog=page.locator('#engine-dialog');await expect(dialog).toContainText('Lowest credible offer: $400.00');await expect(dialog).toContainText('$110.00 per bottle');await expect(dialog).toContainText('Availability: SOLD');await expect(dialog).toContainText('historical_auction');await expect(dialog).toContainText('Bottle/package format differs');await expect(dialog).toContainText('Market offer stale');await expect(dialog.getByRole('button',{name:'Refresh Market Prices'})).toBeDisabled();
  const a=dialog.locator('.evidence-card').filter({has:page.locator('strong', {hasText:'A ·'})});await a.getByRole('button',{name:'Reject match',exact:true}).click();await expect(dialog).toContainText('Market median: $415.00');await expect(dialog).toContainText('Identity match manually rejected');
  await dialog.locator('.evidence-card').filter({has:page.locator('strong',{hasText:'A ·'})}).getByRole('button',{name:'Approve identity match',exact:true}).click();await expect(dialog).toContainText('Market median: $410.00');
  await page.locator('#engine-dialog-close').click();await page.getByLabel('Minimum market discount %',{exact:true}).fill('20');await page.getByLabel('Minimum dollar discount / bottle',{exact:true}).fill('100');await page.getByLabel('Minimum confirmed merchant comps',{exact:true}).fill('3');await expect(results.locator('tbody tr')).toHaveCount(1);await page.getByLabel('Minimum confirmed merchant comps',{exact:true}).fill('4');await expect(results).toContainText('No wines meet these filters.');await page.getByRole('button',{name:'Reset filters'}).click();await page.getByLabel('Rank by',{exact:true}).selectOption('marketContribution');await page.reload();await expect(results).toContainText('$410.00');
});
test('manual checked merchant offer persists; exclusion and merchant corrections survive reimport',async({page})=>{
  await upload(page,'flickinger',[wine]);await page.getByRole('button',{name:'Market Intelligence',exact:true}).click();const dialog=page.locator('#engine-dialog');await expect(dialog).toContainText('No verified current market offers found.');const form=page.locator('#manual-market-form');
  await form.getByLabel('Merchant',{exact:true}).fill('Synthetic Manual Merchant');await form.getByLabel('Offer URL',{exact:true}).fill('https://synthetic-merchant.example/wine-y');await form.getByLabel('Total package price',{exact:true}).fill('420');await form.getByLabel('Last actually checked',{exact:true}).fill(new Date(Date.now()-60000).toISOString().slice(0,16));await form.getByLabel('Stock evidence',{exact:true}).fill('Synthetic observed in-stock fixture only');await form.getByRole('checkbox').check();await form.getByRole('button',{name:'Save offer and re-rank'}).click();await expect(dialog).toContainText('Market median: $420.00');await expect(dialog).toContainText('Low confidence');
  await dialog.getByRole('button',{name:'Exclude offer',exact:true}).click();await expect(dialog).toContainText('Offer manually excluded');await page.locator('#engine-dialog-close').click();await page.reload();await page.getByRole('button',{name:'Market Intelligence',exact:true}).click();await expect(dialog).toContainText('Offer manually excluded');await dialog.getByRole('button',{name:'Restore offer',exact:true}).click();await expect(dialog).toContainText('Market median: $420.00');
  await dialog.getByText('Correct format, merchant reliability or duplicate',{exact:true}).click();const controls=dialog.locator('.market-controls-form');await controls.getByLabel('Merchant reliability',{exact:true}).fill('.5');await controls.getByRole('button',{name:'Save offer corrections'}).click();await expect(dialog).toContainText('Merchant reliability below configured threshold');await page.locator('#engine-dialog-close').click();await upload(page,'flickinger',[wine]);await page.getByRole('button',{name:'Market Intelligence',exact:true}).click();await expect(dialog).toContainText('Merchant reliability below configured threshold');await expect(dialog).toContainText('Synthetic observed in-stock fixture only');
});
