import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import readExcel from 'read-excel-file/node';
import {initialState,ingestDataset} from '../../src/engine/ingestion.js';
const rows=Array.from({length:55},(_,i)=>({raw_title:`Synthetic Estate ${i} Reserve`,producer:`Synthetic Estate ${i}`,cuvee:'Reserve',vintage:2019,format:'6x750ml',price:600+i,WA:90+i/20,country:'France',region:'Bordeaux',type:'Red'}));
async function importData(page,sourceId,data){await page.getByRole('button',{name:'Import data',exact:true}).click();const dialog=page.locator('#engine-dialog');await dialog.getByRole('combobox',{name:'Import source',exact:true}).selectOption(sourceId);await dialog.getByLabel('Excel, CSV or JSON file').setInputFiles({name:'synthetic-authorized-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({rows:data}))});await dialog.getByRole('button',{name:'Validate and import',exact:true}).click();await expect(dialog).not.toBeVisible();}
test('existing controls adjust critic weighting, persist filters and produce top 15/50 CSV and Excel',async({page})=>{
 await page.route('**/api/**',r=>r.fulfill({status:404,body:'{}'}));const requests=[];page.on('request',r=>{if(/pricing|market-research/.test(r.url()))requests.push(r.url());});await page.goto('/');await importData(page,'flickinger',rows);
 await expect(page.locator('#engine-results tbody tr')).toHaveCount(55);
 await page.getByRole('button',{name:'Preferences',exact:true}).click();for(const label of ['Regional vintage quality (%)','Critic consensus and confidence (%)'])await page.getByLabel(label,{exact:true}).fill('0');await page.getByLabel('Professional critic scores (%)',{exact:true}).fill('100');await expect(page.locator('#weight-total')).toHaveText('Total: 100%');await page.getByRole('button',{name:'Save preferences and re-rank'}).click();await expect(page.locator('#engine-results tbody tr').first()).toContainText('Synthetic Estate 54 Reserve');
 await page.getByLabel('Minimum critic /100',{exact:true}).fill('91');await expect(page.locator('#engine-results tbody tr')).toHaveCount(35);await page.getByRole('button',{name:'Reset filters',exact:true}).click();
 const csv=page.waitForEvent('download');await page.getByRole('button',{name:'Download CSV shortlist',exact:true}).click();const csvFile=await csv;const text=await readFile(await csvFile.path(),'utf8');expect(text.split('\r\n')).toHaveLength(16);expect(text).toContain('Flickinger lot price');expect(text).toContain('Professional critic scores weight %');
 await page.locator('#shortlist-size').selectOption('50');const xlsx=page.waitForEvent('download');await page.getByRole('button',{name:'Download Excel shortlist',exact:true}).click();const sheets=await readExcel(await (await xlsx).path());expect(sheets[0].data).toHaveLength(51);expect(sheets[0].data[1][0]).toBe(1);
 await page.reload();await expect(page.locator('#engine-results tbody tr').first()).toContainText('Synthetic Estate 54 Reserve');await page.getByRole('button',{name:'Preferences',exact:true}).click();await expect(page.getByLabel('Professional critic scores (%)',{exact:true})).toHaveValue('100');expect(requests).toEqual([]);await expect(page.getByRole('button',{name:'Refresh Prices',exact:true})).toHaveCount(0);
});
test('legacy pricing data is backed up before browser migration and no pricing controls remain',async({page})=>{
 const legacy=ingestDataset(initialState(),'flickinger',{rows:[rows[0]]});delete legacy.qualityModelVersion;legacy.market=[{id:'historic-quote'}];legacy.preferences.weights={value:35,quality:35,vintage:10,window:10,confidence:10};legacy.marketResearch={jobs:[{status:'queued'}]};await page.addInitScript(s=>localStorage.setItem('wine-intelligence.v1',JSON.stringify(s)),legacy);await page.route('**/api/**',r=>r.fulfill({status:404,body:'{}'}));await page.goto('/');await expect(page.locator('#engine-results')).toContainText('$600.00');
 const saved=await page.evaluate(async()=>{const db=await new Promise(resolve=>{const r=indexedDB.open('wine-intelligence',1);r.onsuccess=()=>resolve(r.result);});const get=key=>new Promise(resolve=>{const r=db.transaction('engine').objectStore('engine').get(key);r.onsuccess=()=>resolve(r.result);});const values=[await get('wine-intelligence.v1'),await get('wine-intelligence.before-quality.v1')];db.close();return values;});expect(saved[0].market).toBeUndefined();expect(saved[0].preferences.weights).toEqual({quality:60,vintage:25,consensus:15});expect(saved[1].market[0].id).toBe('historic-quote');await expect(page.locator('#engine-results')).not.toContainText('Market reference');
});
