import {FACTOR_LABELS} from './quality-settings.js';
export function shortlistData(ranked,preferences,limit=15){
  if(!Number.isInteger(limit)||limit<1||limit>10000)throw new Error('Shortlist size must be 1–10000.');
  const seen=new Set(),selected=[];
  for(const row of ranked){if(row.score==null || seen.has(row.wine.beverageId))continue;seen.add(row.wine.beverageId);selected.push(row);if(selected.length===limit)break;}
  return selected.map((a,i)=>{const w=a.wine,l=a.listing,v=a.vintageIntelligence,g=v.geography;return {
    Rank:i+1,Producer:w.producer,'Wine name':w.rawTitle,'Cuvée':w.cuvee,Vineyard:w.vineyard,Vintage:w.rawVintage || w.vintage,Country:g.country || w.country,Region:g.region || w.region,Subregion:g.subregion || w.subregion,Appellation:g.appellation || w.appellation,'Bottle ml':w.bottleMl,'Bottle count':w.packCount,'Lot packaging':w.packaging,Currency:l.currency,'Flickinger lot price':l.price,'Flickinger price per bottle':l.unitPrice,'750ml equivalents':w.packCount*w.bottleMl/750,
    'Professional critic composite':a.quality,'Individual critic scores':a.professional.map(r=>`${r.publication}: ${r.rawScore}/${r.scale} (${r.reviewStage || 'unspecified'}; ${r.verified?'verified':'unverified'})`).join('; '),'Professional critic sources':a.professional.map(r=>r.sourceURL || r.sourceReference || r.sourceName).join('; '),'Vintage assessment':a.vintage,'Vintage scope':v.regionUsed,'Vintage geographic specificity':v.level,'Vintage source':a.assessments.map(r=>`${r.publication}: ${r.sourceURL || r.sourceReference}`).join('; '),'Critic consensus and confidence':a.consensus,'Overall quality score':a.score,'Overall evidence confidence':a.rankingConfidence,'Weighted coverage':a.coverage,'Ranking status':a.rankingStatus,'Verified three-factor coverage':a.verifiedComplete,'Missing-data indicators':a.missingFactors.map(k=>FACTOR_LABELS[k]).join('; '),...Object.fromEntries(Object.entries(preferences.weights).map(([k,v])=>[`${FACTOR_LABELS[k]} weight %`,v]))
  };});
}
const safeCell=v=>typeof v==='string' && /^[\s]*[=+\-@]/.test(v)?"'"+v:v;
export function shortlistCSV(rows){if(!rows.length)return '';const keys=Object.keys(rows[0]),quote=v=>'"'+String(safeCell(v) ?? '').replaceAll('"','""')+'"';return '\uFEFF'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(quote).join(',')).join('\r\n');}
export function shortlistCells(rows){return [Object.keys(rows[0]).map(value=>({value,type:String,fontWeight:'bold'})),...rows.map(r=>Object.values(r).map(value=>({value:value ?? '',type:typeof value==='number'?Number:typeof value==='boolean'?Boolean:String})))];}
export async function exportShortlist(ranked,preferences,limit,kind){const rows=shortlistData(ranked,preferences,limit);if(!rows.length)throw new Error('No ranked wines meet the current filters.');const name=`wine-quality-top-${rows.length}`;if(kind==='excel'){const {default:writeExcel}=await import('write-excel-file/browser');await writeExcel(shortlistCells(rows),{sheet:'Wine quality shortlist',columns:Object.keys(rows[0]).map(()=>({width:24})),stickyRowsCount:1}).toFile(name+'.xlsx');}else{const url=URL.createObjectURL(new Blob([shortlistCSV(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}return rows.length;}
