import {escapeHTML as esc} from './model.js';
export function coverageReport(state,ranked,visible,mode,filters={}) {
 const available=ranked.filter(r=>r.listing.isAvailable),matched=available.filter(r=>r.vintage!=null),missing=available.filter(r=>r.vintage==null);
 const groups=new Map();for(const r of missing){const reason=r.vintageIntelligence.status,key=JSON.stringify([r.wine.region,r.vintageIntelligence.geography.region,reason]);const old=groups.get(key)||{importedRegion:r.wine.region,mappedRegion:r.vintageIntelligence.geography.region,reason,count:0};old.count++;groups.set(key,old);}
 return {generatedAt:new Date().toISOString(),mode,filters:{...filters},inventory:{storedListings:state.listings.length,enabledSourceListings:ranked.length,availableListings:available.length,filteredListings:visible.length},vintages:{savedAssessments:state.vintages.length,enabledAssessments:state.vintages.filter(r=>state.sources.some(s=>s.id===r.sourceId&&s.enabled)).length,matchedAvailableListings:matched.length,matchedFilteredListings:visible.filter(r=>r.vintage!=null).length,unmatchedGroups:[...groups.values()].sort((a,b)=>b.count-a.count)},market:{storedOffers:state.market.length,availableListingsWithComparables:available.filter(r=>r.marketEvidence.length).length,automaticSearchConnected:mode==='server',message:mode==='server'?'Imports preserve existing offers; a separate Market research refresh queues external searches.':'Automatic price retrieval is not connected on this website. Reimporting inventory does not fetch retailer prices.'},unmatchedWines:missing.map(r=>({listingId:r.listing.id,wine:r.wine.rawTitle,vintage:r.wine.rawVintage || r.wine.vintage,importedRegion:r.wine.region,mappedRegion:r.vintageIntelligence.geography.region,appellation:r.vintageIntelligence.geography.appellation,style:r.vintageIntelligence.geography.style,type:r.vintageIntelligence.geography.type,status:r.vintageIntelligence.status,rejectedChartReasons:[...new Set(r.vintageIntelligence.candidates.flatMap(c=>c.match.reasons))]}))};
}
export function coverageDialog(report) {
 const i=report.inventory,v=report.vintages;
 return `<p><strong>${v.matchedAvailableListings} of ${i.availableListings} available listings have vintage ratings across your entire enabled inventory.</strong> Your current filters show ${v.matchedFilteredListings} vintage matches among ${i.filteredListings} listings. These counts refer to retailer listings, which may include separate offers for the same wine.</p><p>${v.savedAssessments} chart assessments saved; ${v.enabledAssessments} enabled. ${i.storedListings} total listings stored, including disabled sources and unavailable offers.</p><p>${esc(report.market.message)} ${report.market.storedOffers} market offers stored; ${report.market.availableListingsWithComparables} available listings have eligible verified comparables.</p><button id="engine-download-coverage" class="button primary">Download coverage report</button><h3>Unmatched vintage groups</h3><div class="terminal-table-wrap"><table class="evidence-table"><thead><tr><th>Imported region</th><th>Mapped region</th><th>Assessment status</th><th>Listings</th></tr></thead><tbody>${v.unmatchedGroups.map(g=>`<tr><td>${esc(g.importedRegion || 'Missing')}</td><td>${esc(g.mappedRegion || 'Unknown')}</td><td>${esc(g.reason)}</td><td>${g.count}</td></tr>`).join('')}</tbody></table></div><p>The download includes the wine names, imported and mapped geography, and assessment status needed to investigate missing matches. Saved inventory is unchanged.</p>`;
}
