import {escapeHTML as esc} from './model.js';
export function criticGapReason(row){
 if(row.quality!=null)return row.criticComposite.verifiedCount?'Verified review available':'Retailer-reported evidence; independent verification missing';
 if(row.listing.criticWarnings?.length)return 'Malformed supplied score; correction required';
 if(/\b(?:nr|not rated)\b/i.test(row.listing.reportedRatings || ''))return 'Publication explicitly marked not rated; other critics unknown';
 if(row.pendingMatches?.some(m=>m.observation.kind==='critic') || row.exclusions?.some(e=>/Review data confidence/.test(e.reason)))return 'Supplied review requires identity or match review';
 return 'No usable score supplied; independent review not searched or search status unknown';
}
export function qualityCoverage(ranked){
 const unique=[...new Map(ranked.filter(r=>r.listing.isAvailable).map(r=>[r.wine.beverageId,r])).values()];const total=unique.length;
 const measures={professional:unique.filter(r=>r.quality!=null).length,multipleProfessional:unique.filter(r=>r.criticComposite.publicationCount>=2).length,verifiedProfessional:unique.filter(r=>r.criticComposite.verifiedCount>0).length,vintage:unique.filter(r=>r.vintage!=null).length,criticConsensus:unique.filter(r=>r.consensus!=null).length,allThree:unique.filter(r=>r.completeThreeFactors).length,verifiedAllThree:unique.filter(r=>r.verifiedComplete).length,missingOne:unique.filter(r=>r.missingFactors.length===1).length,missingMultiple:unique.filter(r=>r.missingFactors.length>1).length,sufficientEvidence:unique.filter(r=>r.reliable).length};
 return {uniqueWineIdentities:total,counts:measures,percentages:Object.fromEntries(Object.entries(measures).map(([k,v])=>[k,total?v*100/total:0])),missingWines:unique.filter(r=>r.missingFactors.length).map(r=>({wineId:r.wine.id,wine:r.wine.rawTitle,vintage:r.wine.rawVintage || r.wine.vintage,region:r.vintageIntelligence.geography.region || r.wine.region,importedRegion:r.wine.region,subregion:r.vintageIntelligence.geography.subregion,appellation:r.vintageIntelligence.geography.appellation,type:r.vintageIntelligence.geography.type,style:r.vintageIntelligence.geography.style,missing:r.missingFactors,reportedRatings:r.listing.reportedRatings || '',parsingWarnings:r.listing.criticWarnings || [],criticReason:criticGapReason(r),criticStatus:r.criticStatus,vintageReason:r.vintageIntelligence.status}))};
}
export function coverageReport(state,ranked,visible,mode,filters={}){
 const available=ranked.filter(r=>r.listing.isAvailable),matched=available.filter(r=>r.vintage!=null),missing=available.filter(r=>r.vintage==null),groups=new Map();
 for(const r of missing){const reason=r.vintageIntelligence.status,key=JSON.stringify([r.wine.region,r.vintageIntelligence.geography.region,reason]);const g=groups.get(key)||{importedRegion:r.wine.region,mappedRegion:r.vintageIntelligence.geography.region,reason,count:0};g.count++;groups.set(key,g);}
 return {generatedAt:new Date().toISOString(),mode,filters:{...filters},inventory:{storedListings:state.listings.length,enabledSourceListings:ranked.length,availableListings:available.length,filteredListings:visible.length},quality:qualityCoverage(ranked),vintages:{savedAssessments:state.vintages.length,enabledAssessments:state.vintages.filter(r=>state.sources.some(s=>s.id===r.sourceId&&s.enabled)).length,matchedAvailableListings:matched.length,matchedFilteredListings:visible.filter(r=>r.vintage!=null).length,unmatchedGroups:[...groups.values()].sort((a,b)=>b.count-a.count)},unmatchedWines:missing.map(r=>({listingId:r.listing.id,wine:r.wine.rawTitle,vintage:r.wine.rawVintage || r.wine.vintage,importedRegion:r.wine.region,mappedRegion:r.vintageIntelligence.geography.region,appellation:r.vintageIntelligence.geography.appellation,style:r.vintageIntelligence.geography.style,type:r.vintageIntelligence.geography.type,status:r.vintageIntelligence.status}))};
}
export function coverageDialog(report){const i=report.inventory,v=report.vintages,q=report.quality;return `<p><strong>${v.matchedAvailableListings} of ${i.availableListings} available listings have vintage ratings across your entire enabled inventory.</strong> Your current filters show ${v.matchedFilteredListings} vintage matches among ${i.filteredListings} listings.</p><p>${q.uniqueWineIdentities} unique wine/vintage identities; separate package offers count once here.</p><table class="evidence-table"><thead><tr><th>Quality coverage</th><th>Wines</th><th>%</th></tr></thead><tbody>${Object.entries(q.counts).map(([k,v])=>`<tr><td>${esc(k.replace(/([A-Z])/g,' $1'))}</td><td>${v}</td><td>${q.percentages[k].toFixed(1)}%</td></tr>`).join('')}</tbody></table><p>Reported critic scores are distinguished from independently verified reviews. Missing scores remain unassessed; no external pricing or community retrieval runs.</p><button id="engine-download-coverage" class="button primary">Download coverage report</button><h3>Unmatched vintage groups</h3><table class="evidence-table"><thead><tr><th>Imported region</th><th>Mapped region</th><th>Status</th><th>Listings</th></tr></thead><tbody>${v.unmatchedGroups.map(g=>`<tr><td>${esc(g.importedRegion || 'Missing')}</td><td>${esc(g.mappedRegion || 'Unknown')}</td><td>${esc(g.reason)}</td><td>${g.count}</td></tr>`).join('')}</tbody></table><p>The report includes missing records and reasons. Original inventory and source observations remain saved.</p>`;}
